-- ============================================================================
-- RBAC 数据初始化脚本 — 主入口
--
-- 【文件拆分说明】
-- 为便于维护，已将权限、角色、分配、用户数据拆分为独立文件：
--
--   文件                                     | 职责
--   ────────────────────────────────────────┼──────────────────────────
--   seed_rbac_01_clean.sql                  | 清理旧数据 + 重置自增ID
--   seed_rbac_02_permissions.sql            | 所有权限定义
--   seed_rbac_03_roles.sql                  | 所有角色定义
--   seed_rbac_04_assignments.sql            | 角色-权限关联分配
--   seed_rbac_05_users.sql                  | 用户数据
--
-- 【执行方式】
-- 方式一（逐条执行）：
--   mysql -u root -p eshop_db < scripts/seed_rbac_01_clean.sql
--   mysql -u root -p eshop_db < scripts/seed_rbac_02_permissions.sql
--   mysql -u root -p eshop_db < scripts/seed_rbac_03_roles.sql
--   mysql -u root -p eshop_db < scripts/seed_rbac_04_assignments.sql
--   mysql -u root -p eshop_db < scripts/seed_rbac_05_users.sql
--
-- 方式二（mysql CLI 内 source）：
--   mysql> source scripts/seed_rbac_01_clean.sql
--   mysql> source scripts/seed_rbac_02_permissions.sql
--   mysql> source scripts/seed_rbac_03_roles.sql
--   mysql> source scripts/seed_rbac_04_assignments.sql
--   mysql> source scripts/seed_rbac_05_users.sql
--
-- 方式三（合并执行）：
--   cat scripts/seed_rbac_0*.sql | mysql -u root -p eshop_db
-- ============================================================================

-- 本文件仅为执行入口说明，请按上述方式执行对应子文件。
